//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("testModel", "usercity_ibfk_1", "city", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tasktab.Models.city), "usercity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tasktab.Models.usercity), true)]
[assembly: EdmRelationshipAttribute("testModel", "useraccessscren_ibfk_1", "useraccess", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tasktab.Models.useraccess), "useraccessscren", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tasktab.Models.useraccessscren), true)]
[assembly: EdmRelationshipAttribute("testModel", "userinfo_ibfk_1", "useraccess", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tasktab.Models.useraccess), "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tasktab.Models.userinfo), true)]

#endregion

namespace tasktab.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testEntities14 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testEntities14 object using the connection string found in the 'testEntities14' section of the application configuration file.
        /// </summary>
        public testEntities14() : base("name=testEntities14", "testEntities14")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities14 object.
        /// </summary>
        public testEntities14(string connectionString) : base(connectionString, "testEntities14")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities14 object.
        /// </summary>
        public testEntities14(EntityConnection connection) : base(connection, "testEntities14")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city> cities
        {
            get
            {
                if ((_cities == null))
                {
                    _cities = base.CreateObjectSet<city>("cities");
                }
                return _cities;
            }
        }
        private ObjectSet<city> _cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<country> countries
        {
            get
            {
                if ((_countries == null))
                {
                    _countries = base.CreateObjectSet<country>("countries");
                }
                return _countries;
            }
        }
        private ObjectSet<country> _countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<login> logins
        {
            get
            {
                if ((_logins == null))
                {
                    _logins = base.CreateObjectSet<login>("logins");
                }
                return _logins;
            }
        }
        private ObjectSet<login> _logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ruletax> ruletaxes
        {
            get
            {
                if ((_ruletaxes == null))
                {
                    _ruletaxes = base.CreateObjectSet<ruletax>("ruletaxes");
                }
                return _ruletaxes;
            }
        }
        private ObjectSet<ruletax> _ruletaxes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<useraccess> useraccesses
        {
            get
            {
                if ((_useraccesses == null))
                {
                    _useraccesses = base.CreateObjectSet<useraccess>("useraccesses");
                }
                return _useraccesses;
            }
        }
        private ObjectSet<useraccess> _useraccesses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<useraccessscren> useraccessscrens
        {
            get
            {
                if ((_useraccessscrens == null))
                {
                    _useraccessscrens = base.CreateObjectSet<useraccessscren>("useraccessscrens");
                }
                return _useraccessscrens;
            }
        }
        private ObjectSet<useraccessscren> _useraccessscrens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usercity> usercities
        {
            get
            {
                if ((_usercities == null))
                {
                    _usercities = base.CreateObjectSet<usercity>("usercities");
                }
                return _usercities;
            }
        }
        private ObjectSet<usercity> _usercities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usercontact> usercontacts
        {
            get
            {
                if ((_usercontacts == null))
                {
                    _usercontacts = base.CreateObjectSet<usercontact>("usercontacts");
                }
                return _usercontacts;
            }
        }
        private ObjectSet<usercontact> _usercontacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userinfo> userinfoes
        {
            get
            {
                if ((_userinfoes == null))
                {
                    _userinfoes = base.CreateObjectSet<userinfo>("userinfoes");
                }
                return _userinfoes;
            }
        }
        private ObjectSet<userinfo> _userinfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocities(city city)
        {
            base.AddObject("cities", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocountries(country country)
        {
            base.AddObject("countries", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologins(login login)
        {
            base.AddObject("logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ruletaxes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToruletaxes(ruletax ruletax)
        {
            base.AddObject("ruletaxes", ruletax);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the useraccesses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouseraccesses(useraccess useraccess)
        {
            base.AddObject("useraccesses", useraccess);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the useraccessscrens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouseraccessscrens(useraccessscren useraccessscren)
        {
            base.AddObject("useraccessscrens", useraccessscren);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usercities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousercities(usercity usercity)
        {
            base.AddObject("usercities", usercity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usercontacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousercontacts(usercontact usercontact)
        {
            base.AddObject("usercontacts", usercontact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserinfoes(userinfo userinfo)
        {
            base.AddObject("userinfoes", userinfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="city")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city object.
        /// </summary>
        /// <param name="cityid">Initial value of the cityid property.</param>
        /// <param name="cityname">Initial value of the cityname property.</param>
        public static city Createcity(global::System.Int32 cityid, global::System.String cityname)
        {
            city city = new city();
            city.cityid = cityid;
            city.cityname = cityname;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cityid
        {
            get
            {
                return _cityid;
            }
            set
            {
                if (_cityid != value)
                {
                    OncityidChanging(value);
                    ReportPropertyChanging("cityid");
                    _cityid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cityid");
                    OncityidChanged();
                }
            }
        }
        private global::System.Int32 _cityid;
        partial void OncityidChanging(global::System.Int32 value);
        partial void OncityidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cityname
        {
            get
            {
                return _cityname;
            }
            set
            {
                OncitynameChanging(value);
                ReportPropertyChanging("cityname");
                _cityname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cityname");
                OncitynameChanged();
            }
        }
        private global::System.String _cityname;
        partial void OncitynameChanging(global::System.String value);
        partial void OncitynameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "usercity_ibfk_1", "usercity")]
        public EntityCollection<usercity> usercities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usercity>("testModel.usercity_ibfk_1", "usercity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usercity>("testModel.usercity_ibfk_1", "usercity", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new country object.
        /// </summary>
        /// <param name="countryid">Initial value of the countryid property.</param>
        /// <param name="countryname">Initial value of the countryname property.</param>
        public static country Createcountry(global::System.Int32 countryid, global::System.String countryname)
        {
            country country = new country();
            country.countryid = countryid;
            country.countryname = countryname;
            return country;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 countryid
        {
            get
            {
                return _countryid;
            }
            set
            {
                if (_countryid != value)
                {
                    OncountryidChanging(value);
                    ReportPropertyChanging("countryid");
                    _countryid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("countryid");
                    OncountryidChanged();
                }
            }
        }
        private global::System.Int32 _countryid;
        partial void OncountryidChanging(global::System.Int32 value);
        partial void OncountryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countryname
        {
            get
            {
                return _countryname;
            }
            set
            {
                OncountrynameChanging(value);
                ReportPropertyChanging("countryname");
                _countryname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("countryname");
                OncountrynameChanged();
            }
        }
        private global::System.String _countryname;
        partial void OncountrynameChanging(global::System.String value);
        partial void OncountrynameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new login object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static login Createlogin(global::System.Int32 id, global::System.String username, global::System.String password)
        {
            login login = new login();
            login.id = id;
            login.username = username;
            login.password = password;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="ruletax")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ruletax : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ruletax object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="taxname">Initial value of the taxname property.</param>
        /// <param name="amount">Initial value of the amount property.</param>
        /// <param name="levels">Initial value of the levels property.</param>
        public static ruletax Createruletax(global::System.Int32 id, global::System.String taxname, global::System.String amount, global::System.String levels)
        {
            ruletax ruletax = new ruletax();
            ruletax.id = id;
            ruletax.taxname = taxname;
            ruletax.amount = amount;
            ruletax.levels = levels;
            return ruletax;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String taxname
        {
            get
            {
                return _taxname;
            }
            set
            {
                OntaxnameChanging(value);
                ReportPropertyChanging("taxname");
                _taxname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("taxname");
                OntaxnameChanged();
            }
        }
        private global::System.String _taxname;
        partial void OntaxnameChanging(global::System.String value);
        partial void OntaxnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.String _amount;
        partial void OnamountChanging(global::System.String value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String levels
        {
            get
            {
                return _levels;
            }
            set
            {
                OnlevelsChanging(value);
                ReportPropertyChanging("levels");
                _levels = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("levels");
                OnlevelsChanged();
            }
        }
        private global::System.String _levels;
        partial void OnlevelsChanging(global::System.String value);
        partial void OnlevelsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="useraccess")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class useraccess : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new useraccess object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="role">Initial value of the role property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static useraccess Createuseraccess(global::System.Int32 id, global::System.String role, global::System.String description)
        {
            useraccess useraccess = new useraccess();
            useraccess.id = id;
            useraccess.role = role;
            useraccess.description = description;
            return useraccess;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.String _role;
        partial void OnroleChanging(global::System.String value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "useraccessscren_ibfk_1", "useraccessscren")]
        public EntityCollection<useraccessscren> useraccessscrens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<useraccessscren>("testModel.useraccessscren_ibfk_1", "useraccessscren");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<useraccessscren>("testModel.useraccessscren_ibfk_1", "useraccessscren", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userinfo_ibfk_1", "userinfo")]
        public EntityCollection<userinfo> userinfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<userinfo>("testModel.userinfo_ibfk_1", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<userinfo>("testModel.userinfo_ibfk_1", "userinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="useraccessscren")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class useraccessscren : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new useraccessscren object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="modulename">Initial value of the modulename property.</param>
        /// <param name="useraccessid">Initial value of the useraccessid property.</param>
        public static useraccessscren Createuseraccessscren(global::System.Int32 id, global::System.String modulename, global::System.Int32 useraccessid)
        {
            useraccessscren useraccessscren = new useraccessscren();
            useraccessscren.id = id;
            useraccessscren.modulename = modulename;
            useraccessscren.useraccessid = useraccessid;
            return useraccessscren;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modulename
        {
            get
            {
                return _modulename;
            }
            set
            {
                OnmodulenameChanging(value);
                ReportPropertyChanging("modulename");
                _modulename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("modulename");
                OnmodulenameChanged();
            }
        }
        private global::System.String _modulename;
        partial void OnmodulenameChanging(global::System.String value);
        partial void OnmodulenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 useraccessid
        {
            get
            {
                return _useraccessid;
            }
            set
            {
                OnuseraccessidChanging(value);
                ReportPropertyChanging("useraccessid");
                _useraccessid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("useraccessid");
                OnuseraccessidChanged();
            }
        }
        private global::System.Int32 _useraccessid;
        partial void OnuseraccessidChanging(global::System.Int32 value);
        partial void OnuseraccessidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> adddata
        {
            get
            {
                return _adddata;
            }
            set
            {
                OnadddataChanging(value);
                ReportPropertyChanging("adddata");
                _adddata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adddata");
                OnadddataChanged();
            }
        }
        private Nullable<global::System.Boolean> _adddata;
        partial void OnadddataChanging(Nullable<global::System.Boolean> value);
        partial void OnadddataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> editdata
        {
            get
            {
                return _editdata;
            }
            set
            {
                OneditdataChanging(value);
                ReportPropertyChanging("editdata");
                _editdata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("editdata");
                OneditdataChanged();
            }
        }
        private Nullable<global::System.Boolean> _editdata;
        partial void OneditdataChanging(Nullable<global::System.Boolean> value);
        partial void OneditdataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> deletedata
        {
            get
            {
                return _deletedata;
            }
            set
            {
                OndeletedataChanging(value);
                ReportPropertyChanging("deletedata");
                _deletedata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deletedata");
                OndeletedataChanged();
            }
        }
        private Nullable<global::System.Boolean> _deletedata;
        partial void OndeletedataChanging(Nullable<global::System.Boolean> value);
        partial void OndeletedataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "useraccessscren_ibfk_1", "useraccess")]
        public useraccess useraccess
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.useraccessscren_ibfk_1", "useraccess").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.useraccessscren_ibfk_1", "useraccess").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<useraccess> useraccessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.useraccessscren_ibfk_1", "useraccess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<useraccess>("testModel.useraccessscren_ibfk_1", "useraccess", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="usercity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usercity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usercity object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="cityid">Initial value of the cityid property.</param>
        public static usercity Createusercity(global::System.Int32 id, global::System.String name, global::System.String address, global::System.String phone, global::System.Int32 cityid)
        {
            usercity usercity = new usercity();
            usercity.id = id;
            usercity.name = name;
            usercity.address = address;
            usercity.phone = phone;
            usercity.cityid = cityid;
            return usercity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cityid
        {
            get
            {
                return _cityid;
            }
            set
            {
                OncityidChanging(value);
                ReportPropertyChanging("cityid");
                _cityid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cityid");
                OncityidChanged();
            }
        }
        private global::System.Int32 _cityid;
        partial void OncityidChanging(global::System.Int32 value);
        partial void OncityidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "usercity_ibfk_1", "city")]
        public city city
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("testModel.usercity_ibfk_1", "city").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("testModel.usercity_ibfk_1", "city").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> cityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("testModel.usercity_ibfk_1", "city");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("testModel.usercity_ibfk_1", "city", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="usercontact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usercontact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usercontact object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static usercontact Createusercontact(global::System.Int32 id, global::System.String name, global::System.String address, global::System.String phone)
        {
            usercontact usercontact = new usercontact();
            usercontact.id = id;
            usercontact.name = name;
            usercontact.address = address;
            usercontact.phone = phone;
            return usercontact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="userinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userinfo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="roleid">Initial value of the roleid property.</param>
        public static userinfo Createuserinfo(global::System.Int32 id, global::System.String name, global::System.String email, global::System.String password, global::System.String phone, global::System.Int32 roleid)
        {
            userinfo userinfo = new userinfo();
            userinfo.id = id;
            userinfo.name = name;
            userinfo.email = email;
            userinfo.password = password;
            userinfo.phone = phone;
            userinfo.roleid = roleid;
            return userinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleid
        {
            get
            {
                return _roleid;
            }
            set
            {
                OnroleidChanging(value);
                ReportPropertyChanging("roleid");
                _roleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleid");
                OnroleidChanged();
            }
        }
        private global::System.Int32 _roleid;
        partial void OnroleidChanging(global::System.Int32 value);
        partial void OnroleidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel", "userinfo_ibfk_1", "useraccess")]
        public useraccess useraccess
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.userinfo_ibfk_1", "useraccess").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.userinfo_ibfk_1", "useraccess").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<useraccess> useraccessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<useraccess>("testModel.userinfo_ibfk_1", "useraccess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<useraccess>("testModel.userinfo_ibfk_1", "useraccess", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
